language: swift
osx_image: xcode9.3

install: true

before_install:
 - gem install cocoapods
 - pod --version

script:
 - cd Example
 - pod repo update && pod update
 - set -o pipefail
 - xcodebuild -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - travis_wait 30 pod lib lint Constrictor.podspec
